# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: UiPathPack@2
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    orchestratorConnection: 'orchestrator1'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
- task: UiPathDeploy@2
      inputs:
        orchestratorConnection: 'orchestrator1'
        packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
        folderName: 'Shared'
